CREATE TABLE crypto_wallets (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT NOT NULL,
    network            VARCHAR(16) NOT NULL,
    address            VARCHAR(160) NOT NULL,
    address_normalized VARCHAR(160) NOT NULL,
    label              VARCHAR(255),
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    is_archived        BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_crypto_wallets_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_crypto_wallets_user ON crypto_wallets(user_id);
CREATE UNIQUE INDEX uq_crypto_wallets_user_network_address ON crypto_wallets(user_id, network, address_normalized);

