CREATE TABLE fx_rates (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_currency VARCHAR(10) NOT NULL,
    quote_currency VARCHAR(10) NOT NULL,
    rate          NUMERIC(19,12) NOT NULL,
    as_of         TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_fx_rates_base_quote_asof UNIQUE (base_currency, quote_currency, as_of)
);

CREATE INDEX idx_fx_rates_base_asof ON fx_rates(base_currency, as_of);
CREATE INDEX idx_fx_rates_base_quote_asof ON fx_rates(base_currency, quote_currency, as_of);

