CREATE TABLE rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    params_json TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    last_triggered_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_rules_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_rules_user ON rules(user_id);
CREATE INDEX idx_rules_status ON rules(status);
CREATE INDEX idx_rules_user_status ON rules(user_id, status);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    rule_id BIGINT NOT NULL,
    message TEXT NOT NULL,
    period_start DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    read_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_notifications_rule FOREIGN KEY (rule_id) REFERENCES rules(id)
);

CREATE INDEX idx_notifications_user ON notifications(user_id);
CREATE INDEX idx_notifications_created_at ON notifications(created_at);
CREATE INDEX idx_notifications_read_at ON notifications(read_at);
CREATE INDEX idx_notifications_rule ON notifications(rule_id);
CREATE UNIQUE INDEX uq_notifications_rule_period ON notifications(rule_id, period_start);
