CREATE TABLE crypto_wallet_analysis_jobs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    wallet_id     BIGINT NOT NULL,
    status        VARCHAR(16) NOT NULL,
    stage         VARCHAR(32) NOT NULL,
    progress_pct  INTEGER NOT NULL DEFAULT 0,
    error_message VARCHAR(500),
    started_at    TIMESTAMP WITH TIME ZONE,
    finished_at   TIMESTAMP WITH TIME ZONE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_crypto_wallet_analysis_jobs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_crypto_wallet_analysis_jobs_wallet FOREIGN KEY (wallet_id) REFERENCES crypto_wallets(id) ON DELETE CASCADE
);

CREATE INDEX idx_crypto_wallet_analysis_jobs_wallet_created
    ON crypto_wallet_analysis_jobs(wallet_id, created_at DESC);

CREATE INDEX idx_crypto_wallet_analysis_jobs_user_created
    ON crypto_wallet_analysis_jobs(user_id, created_at DESC);
