ALTER TABLE crypto_wallet_analysis_jobs
    ADD COLUMN last_successful_stage VARCHAR(32);

CREATE TABLE wallet_tx_raw (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    wallet_id BIGINT NOT NULL,
    network VARCHAR(16) NOT NULL,
    tx_hash VARCHAR(128) NOT NULL,
    log_index BIGINT NOT NULL DEFAULT 0,
    tx_at TIMESTAMP WITH TIME ZONE NOT NULL,
    block_number BIGINT,
    direction VARCHAR(8),
    asset_code VARCHAR(24),
    amount NUMERIC(38, 18),
    amount_usd NUMERIC(38, 18),
    fee_usd NUMERIC(38, 18),
    counterparty VARCHAR(256),
    source VARCHAR(32) NOT NULL,
    raw_payload TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_wallet_tx_raw_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_wallet_tx_raw_wallet FOREIGN KEY (wallet_id) REFERENCES crypto_wallets(id) ON DELETE CASCADE,
    CONSTRAINT uq_wallet_tx_raw_wallet_hash_log UNIQUE (wallet_id, tx_hash, log_index)
);

CREATE INDEX idx_wallet_tx_raw_wallet_tx_at
    ON wallet_tx_raw(wallet_id, tx_at);

CREATE INDEX idx_wallet_tx_raw_user_tx_at
    ON wallet_tx_raw(user_id, tx_at);

CREATE TABLE wallet_tx_enriched (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    wallet_id BIGINT NOT NULL,
    raw_tx_id BIGINT,
    tx_hash VARCHAR(128) NOT NULL,
    log_index BIGINT NOT NULL DEFAULT 0,
    tx_at TIMESTAMP WITH TIME ZONE NOT NULL,
    direction VARCHAR(8),
    asset_code VARCHAR(24),
    amount NUMERIC(38, 18),
    amount_usd NUMERIC(38, 18),
    category VARCHAR(64),
    counterparty_normalized VARCHAR(160),
    recurring_candidate BOOLEAN NOT NULL DEFAULT FALSE,
    confidence NUMERIC(5, 4),
    source VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_wallet_tx_enriched_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_wallet_tx_enriched_wallet FOREIGN KEY (wallet_id) REFERENCES crypto_wallets(id) ON DELETE CASCADE,
    CONSTRAINT fk_wallet_tx_enriched_raw FOREIGN KEY (raw_tx_id) REFERENCES wallet_tx_raw(id) ON DELETE SET NULL,
    CONSTRAINT uq_wallet_tx_enriched_wallet_hash_log UNIQUE (wallet_id, tx_hash, log_index)
);

CREATE INDEX idx_wallet_tx_enriched_wallet_tx_at
    ON wallet_tx_enriched(wallet_id, tx_at);

CREATE INDEX idx_wallet_tx_enriched_wallet_counterparty_tx_at
    ON wallet_tx_enriched(wallet_id, counterparty_normalized, tx_at);

CREATE TABLE wallet_daily_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    wallet_id BIGINT NOT NULL,
    snapshot_day DATE NOT NULL,
    portfolio_usd NUMERIC(38, 18),
    inflow_usd NUMERIC(38, 18),
    outflow_usd NUMERIC(38, 18),
    net_flow_usd NUMERIC(38, 18),
    pnl_usd NUMERIC(38, 18),
    pnl_pct NUMERIC(12, 6),
    source VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_wallet_daily_snapshots_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_wallet_daily_snapshots_wallet FOREIGN KEY (wallet_id) REFERENCES crypto_wallets(id) ON DELETE CASCADE,
    CONSTRAINT uq_wallet_daily_snapshots_wallet_day UNIQUE (wallet_id, snapshot_day)
);

CREATE INDEX idx_wallet_daily_snapshots_wallet_day
    ON wallet_daily_snapshots(wallet_id, snapshot_day);

CREATE TABLE wallet_insights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    wallet_id BIGINT NOT NULL,
    insight_type VARCHAR(64) NOT NULL,
    title VARCHAR(160) NOT NULL,
    insight_value NUMERIC(38, 8),
    unit VARCHAR(24),
    currency VARCHAR(16),
    label VARCHAR(160),
    avg_amount NUMERIC(38, 8),
    next_estimated_charge_at TIMESTAMP WITH TIME ZONE,
    confidence NUMERIC(5, 4),
    synthetic BOOLEAN NOT NULL DEFAULT FALSE,
    source VARCHAR(32) NOT NULL,
    as_of TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_wallet_insights_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_wallet_insights_wallet FOREIGN KEY (wallet_id) REFERENCES crypto_wallets(id) ON DELETE CASCADE
);

CREATE INDEX idx_wallet_insights_wallet_type_as_of
    ON wallet_insights(wallet_id, insight_type, as_of DESC);

CREATE INDEX idx_wallet_insights_user_as_of
    ON wallet_insights(user_id, as_of DESC);

CREATE INDEX idx_transactions_user_transaction_date
    ON transactions(user_id, transaction_date DESC);

CREATE INDEX idx_transactions_user_category_transaction_date
    ON transactions(user_id, category_id, transaction_date);

-- Retention policy is enforced by scheduled cleanup in application code:
-- wallet_tx_raw 90d, wallet_daily_snapshots/wallet_insights 365d.
