CREATE TABLE IF NOT EXISTS password_reset_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    jti VARCHAR(255) NOT NULL UNIQUE,
    ip_hash VARCHAR(128),
    user_agent_hash VARCHAR(128),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_password_reset_sessions_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_password_reset_sessions_user ON password_reset_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_password_reset_sessions_expires ON password_reset_sessions(expires_at);
