CREATE TABLE IF NOT EXISTS pending_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    base_currency VARCHAR(10) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'USER',
    verify_token_hash VARCHAR(128) NOT NULL,
    verify_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pending_registrations_expires ON pending_registrations(verify_expires_at);
